A ConfigMap is an API object used to store non-confidential data in key-value pairs. 
Pods can consume ConfigMaps as environment variables, 
command-line arguments, or as configuration files in a volume.

apiversion: v1
kind: configmap
metadata:
   name:
data:
  appcolour:
  appmode:

to add config map to pod
add in the image section 
envFrom:
  - configMapRef:
          name:

