apiVersion: v1
kind: PersistentVolume
metadata:
  name: harris-pv
  labels:
    type: harris-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  awsElasticBlockStore:
    volumeID: vol-099024b45c7687c28
    fsType: ext4
