apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harris-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
  volumeName: harris-pv
